### ISSUE TITLE
SyntaxError: can use starred expression only as assignment target

### ISSUE THREAD

**Issue by Plancalkuele** [bastibe/transplant#37] opened 2017-06-26 22:29 UTC
Hi Basti,
I receive the following error for transplant installed in a  Ubuntu 14.04, miniconda3 (Python3.4) environment:
```
Traceback (most recent call last):
  File "Python-Interface_Transplant.py", line 6, in <module>
    import transplant
  File "/home/user/miniconda3/envs/transplant/lib/python3.4/site-packages/transplant/__init__.py", line 1, in <module>
    from .transplant_master import Matlab, TransplantError, MatlabStruct
  File "/home/user/miniconda3/envs/transplant/lib/python3.4/site-packages/transplant/transplant_master.py", line 524
    search_dirs = [*(os.getenv('LD_LIBRARY_PATH') or '').split(':'),
                              ^
SyntaxError: can use starred expression only as assignment target
```

Here is the list of installed packages in this environment:
```
chaospy                   2.2.3                     <pip>
cycler                    0.10.0                    <pip>
decorator                 4.0.11                    <pip>
f90wrap                   0.1.4                     <pip>
libsodium                 1.0.10                        0  
matplotlib                2.0.2                     <pip>
msgpack-python            0.4.8                     <pip>
networkx                  1.11                      <pip>
numpy                     1.13.0                    <pip>
openssl                   1.0.2l                        0  
pip                       9.0.1                    py34_1  
pyparsing                 2.2.0                     <pip>
python                    3.4.5                         0  
python-dateutil           2.6.0                     <pip>
pytz                      2017.2                    <pip>
pyzmq                     16.0.2                    <pip>
readline                  6.2                           2  
scipy                     0.19.1                    <pip>
setuptools                27.2.0                   py34_0  
six                       1.10.0                    <pip>
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
transplant                0.7.8                     <pip>
wheel                     0.29.0                   py34_0  
xz                        5.2.2                         1  
zeromq                    4.1.5                         0  
zlib                      1.2.8                         3 
```

I'm not sure if this is a syntax error or if I should try to set the [LD_LIBRARY_PATH](https://conda.io/docs/troubleshooting.html#resolution-for-c-libraries-unset-the-environment-variables-ld-library-path-on-linux-and-dyld-library-path-on-os-x) although the transplant package was installed in the environment.

**Comment by bastibe** [comment] 2017-06-27 06:54
The syntax error is caused by the `*` operator, which is not supported in Python < 3.5. 

Is using Python >= 3.5 an option for you?

**Comment by bastibe** [comment] 2017-06-27 07:02
Should be fixed in 0.7.9

**Comment by Plancalkuele** [comment] 2017-06-27 08:29
Yep. Works now! Thanks for the quick fix and your efforts for providing a Matlab/Python Interface.

**Comment by bastibe** [comment] 2017-06-27 10:56
My pleasure!

**Closed by bastibe** 2017-06-27 10:56 UTC
